### ISSUE TITLE
Error at VoicePackV6::GenericResponse

### ISSUE THREAD

**Issue by Taomyn** [EDDiscovery/EDDiscovery#1557]
How can I help diagnose this error?

```
Error at VoicePackV6::GenericResponse Step 3: Line 1325:
Set Function indirect: Function hnum: Parameter number be a number
```

I upgraded to v9.0.1.0 and when I had exited ED I saw this mentioned twice in a row - I was at an engineer's station. I can't find anything in the trace log so not sure where else to look.

**Comment by robbyxp1** [comment]
Find the find the journal record where this occurs, right click on it and "Run Actions on this entry".. 

when you find it and it prints out that error, can you 1) tell us at least what journal record it is (print out the whole line including the description field) and if possible 2) find it in the journal itself (if you know how to find them).  1) may be enough

ta.

**Comment by robbyxp1** [comment]
Sorry to be clear,

.. find the journal record itself.. in the journal files located in c:\users\<your user>\Saved Games\Frontier Developments\Elite Dangerous.  A dump of either the whole journal file or just the record would be good.

**Comment by Taomyn** [comment]
Thanks, found one of the issues the one I'd been having for a while, seems the pronunciation for the Electra system was mangled the first character was weird, so I corrected it from Wikipedia to:

`Static say_tx_star21 = r;\b(Electra)\b;<phoneme alphabet='ipa' ph = 'ɪˈlɛktrə'>Electra</phoneme>
`

I'll keep an eye out for the other one and report it separately as it could be a while. But that right-click action was handy for testing this one, cheers.

**Comment by robbyxp1** [comment]
I'm looking into this now, have an update tomorrow.

If you have the keypack also installed F5 does the Run Actions on this entry using the keyboard.

**Comment by Taomyn** [comment]
Probably the new Type-10 causing this one

`{
  "timestamp": "2017-12-20T18:31:41Z",
  "event": "ModuleBuy",
  "Slot": "Military01",
  "BuyItem": "$int_hullreinforcement_size5_class2_name;",
  "BuyItem_Localised": "Hull Reinforcement",
  "BuyPrice": 372938,
  "Ship": "type9_military",
  "ShipID": 35
}`

**Comment by robbyxp1** [comment]
First, we still don't know what is causing hnum to fail - this is due to a journal record EDD expects to be a number not being present or corrupted.

Secondly, after experimentation, IVONA voices fail with SSML phonemes that the microsoft voice do not fail with.  And some of those substitutions in the voice pack do not work at all.

I'm going to put a phoneme off option into the VP.  There are so many different voices across languages and providers its hard to code for all situations.

**Comment by robbyxp1** [comment]
Voice pack 6.0.2 has the phonemes validated against a few voices, so they do not produce that warning.  Also a SSML off option is now in the voice configuration menu.

**Comment by Taomyn** [comment]
Cool, great news - I know there was at least one more that was causing the error but I couldn't track it down. I will update tonight.

Thankfully with the Notepad++ compare plug-in I can easily transfer my personal changes at each update.

**Comment by Taomyn** [comment]
I updated last night and never had the problem again, thanks
