### ISSUE TITLE
Weberver issues

### ISSUE THREAD

**Issue by Loceka** [EDDiscovery/EDDiscovery#3300]
Hello,

I've been trying to use the local webserver and I've run into 2 problems.

The 1st problem is that setting the port to something else than 6502 doesn't work, or more accurately isn't taken into account : the port sticks to 6502 regardless of the chosen value.

The 2nd problem is that the web socket server doesn't seem to be working on my machine (cf. screenshot).
I'm running it on a 64bits Windows 7 operating system and have tried using Firefox, Chrome, Opera and Vivaldi to access the web page.

The Firefox debugger holds on that line
```
const secretGlobals = {
    ...
    encrypt: window.crypto.subtle.encrypt.bind(window.crypto.subtle),
```
Throwing : "**TypeError: window.crypto.subtle is undefined**".

PS:
I have been using other websocket servers (and clients) on that very machine without any problems.

Screenshot:
![EDD_ws_error](https://user-images.githubusercontent.com/7732470/185203751-fb763327-72bc-4ff6-a009-047bf375f0ef.png)

**Comment by Eahlstan** [comment]
Partly this is because the old rule is not deleted.
`remove-netfirewallrule -Name EDDiscovery`
should be performed so that the powershell script doesn't error out.
Still the new port isn't used after this, we will need to look into it.

Thanks for your report.

**Comment by Eahlstan** [comment]
The other reason seems to be that WebServerPort isn't written to the DB. Because of this it falls back to the default port.
Manually adding WebServerPort with an Int of 12345 makes EDD use that port.

**Comment by Eahlstan** [comment]
Fixed by https://github.com/EDDiscovery/EDDiscovery/pull/3301

Thanks again for the report.

**Comment by Loceka** [comment]
Thanks for the quick reply and actions!

It looks like "remove-netfirewallrule" isn't supported by Windows 7.

I've tried to manually add EDDiscovery to the firewall exceptions, even to disable the firewall altogether but to no avail. I still have this JS error.

I'll try to tweak the JS later to make it work

**Comment by Eahlstan** [comment]
Some features of EDDiscovery aren't compatible with Windows 7. Most of the encryption libraries required by external sites (EDDN, EDSM, ...) aren't supported and thus communicating with them no longer works.
Windows 7 doesn't get PowerShell updates any longer too, and NetSecurity is one of the modules that isn't available on W7.
Windows 7 is deprecated for several years now, so no work will be put into any Windows 7 related problems, sorry.

The "good" news is that the WebServer doesn't rely on these automated scripts, as long as you manually do these things it works just fine (click "no" not "yes").
(To get the port change to work you either have to compile a version with the fix yourself or wait for the next release.)

**Comment by Loceka** [comment]
> netsh is available on W7, maybe performing the second part of the script fixes your problem? 
> `netsh http add urlacl url=http://*:6502 user="USERDOMAIN\\USERNAME\"`

Unfortunately no :-/
Besides it was already declared in ACL, for some reason

I thank you a lot for taking time trying to solve this for an old OS, really :)

**Comment by Eahlstan** [comment]
Try if your internet options are too restrictive. Use the search box of your start menu and search for "internet options" go to the security tab and try if something is too strict there.
I'm a bit confused by the fact that you do see part of the site though. You didn't restrict javascript in your browser, didn't you?

**Comment by Loceka** [comment]
Same with the lowest internet options security settings.

And no, I didn't restrict any JS in my browser.

In fact as I said in my first post, I do use websockets for personal projects on this computer (not on that port however, but after changing the value in db I still have the same problem), and using the same Javascript WebSocket class...

Unfortunately I'm not confortable with DotNet so I'll have a hard time debugging that part

**Comment by klightspeed** [comment]
Many browsers require a SSL context before they will expose `window.crypto.subtle`
<https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto>
> Secure context: This feature is available only in [secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) (HTTPS), in some or all [supporting browsers](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto#browser_compatibility).

**Comment by Eahlstan** [comment]
> Many browsers require a SSL context before they will expose `window.crypto.subtle` https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto
> 
> > Secure context: This feature is available only in [secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) (HTTPS), in some or all [supporting browsers](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto#browser_compatibility).
> 
> Edit: Firefox apparently does support it on 127.0.0.1, but not on the LAN

So if it's only used on the localhost accessing it using 127.0.0.1:6502 or localhost:6502 should work fine.
I don't think that Robby will make it use SSL (and if he would: it's Windows 7 so it wouldn't work).
I have no problems using http://192.168.0.61:6502/ on Chrome though, so maybe giving Chrome another shot...

(And I didn't see any crypto thing regarding the site in the code, so where is this SubtleCrypto thing coming from?)

**Comment by klightspeed** [comment]
> (And I didn't see any crypto thing regarding the site in the code, so where is this SubtleCrypto thing coming from?)

Possibly an extension?

**Comment by Loceka** [comment]
> And I didn't see any crypto thing regarding the site in the code, so where is this SubtleCrypto thing coming from?
I've tried looking for it in the code and can't see where it comes from. It also appears to be a FF only thing.

> Edit: Firefox apparently does support it on 127.0.0.1, but not on the LAN
True! Using localhost doesn't throw the subtleCrypto exception, but unfortunately it doesn't change a thing regarding the websocket

I've tried to reach the websocket server using a really simple JS code and :
- I can reach a websocket server created in Java on port 12345
- I __can't__ reach the websocket server of EDD on port 12346

Searching for Windows 7 specific issues with websockets, I found out that using native WebSocket service (through netHttpBinding) doesn't work : https://stackoverflow.com/questions/11039438/using-websocket-on-windows-7

I've tried searching the sources to see what method EDD used but I was challenged by my DotNet ignorance, I could only see that it was created by "AddWebSocketsResponder" from Server, but couldn't find out how that Server class was created or where it came from.

Anyway I believe it's a Windows 7 specific issue, and the only possible fix would be to use a third party library to create the websocket server, that wouldn't rely on native calls. And I believe there is no reason to mess up that bad with the code for an unsupported OS.

I'm closing this issue, thank you both for the time spent trying to fix this!
